version: '3'

volumes:
  laravel-api-database:
    external: true

networks:
  laravel-api-network:
    external: true

services:
  laravel-api:
    image: ambientum/php:7.4-nginx
    container_name: laravel-api
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    networks:
      - laravel-api-network

  laravel-api-database:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - laravel-api-database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    networks:
      - laravel-api-network
